README.md

https://github.com/yahavi/jfrog-vscode-extension/tree/proxy-instructions#proxy

Add proxy instructions

---

package.json
src/main/utils/goUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts
src/test/tests/pypiUtils.test.ts

Allow excluding paths from scan 

---

package.json

* Add new relevant keywords: maven, go, gocenter and more. Rearrange by abc.
* Add homepage

Improve marketplace page

---

src/test/tests/goCenterClient.test.ts

Fix GoCenter client tests

---

package.json
src/extension.ts
src/main/commands/commandManager.ts
src/main/constants/contextKeys.ts
src/main/exclusions/abstractExclusion.ts
src/main/exclusions/exclusionsManager.ts
src/main/exclusions/mavenExclusion.ts
src/main/focus/mavenFocus.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
src/main/utils/mavenUtils.ts
src/test/tests/maven.test.ts

Allow excluding Maven dependency from tree

---

src/test/tests/goCenterClient.test.ts

Fix GoCenter test

---

src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts

-----
Fix an issue caused by:
https://github.com/jfrog/jfrog-vscode-extension/pull/59/files

Set tooltip & description in generalInfo setter - fix

---

README.md

Add NuGet projects section to README

---

README.md

Update .NET documentation

---

package-lock.json
package.json
src/main/commands/commandManager.ts

-----
Add "Copy to clipboard" feature.
Copy by clicking on the Copy button:

Allow copy to clipboard

---

.gitignore
package-lock.json
package.json
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/nugetTree.ts
src/test/tests/nugetUtils.test.ts

Depends on the release of nuget-deps-tree after [nuget-deps-tree#5](https://github.com/jfrog/nuget-deps-tree/pull/5).

Update nuget-deps-tree Api

---

package-lock.json
package.json
releaseScripts/package-lock.json
releaseScripts/package.json

Upgrade depedencies

---

README.md
package.json

-----
Add "New to JFrog Xray? [Start for free](https://jfrog.com/xray/start-free)" in the README  and in the welcome view.

Add instructions for new users

---

.gitignore
.vscode/launch.json
.vscodeignore
package-lock.json
package.json
src/main/dependencyUpdate/dependencyUpdateManager.ts
src/main/treeDataProviders/dependenciesTree/buildsDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
src/main/utils/builds/buildsScanCache.ts
src/main/utils/builds/ciManager.ts
src/main/utils/goUtils.ts
src/main/utils/iconsPaths.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/nugetUtils.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts
src/main/utils/translators.ts
webpack.config.js

-----
Possibly resolves #109 
**Results:**
Activation time drops by around 90% from ~300 to ~30.
Extension size drops from 2.6M to 366K

Bundle plugin with Webpack

---

package-lock.json
package.json
webpack.config.js

Update nuget-deps-tree to 0.2.2

---

package.json

Improve welcome view

---

package-lock.json
package.json
src/main/connect/connectionManager.ts
src/test/tests/issuesDataProvider.test.ts
src/test/tests/scanCacheManager.test.ts

Update dependencies and fix tests

---

src/main/connect/connectionManager.ts
src/main/scanCache/buildsScanCache.ts
src/main/utils/builds/ciManager.ts
src/main/utils/configuration.ts

Support projects in CI mode

---

src/main/scanCache/scanCacheManager.ts
src/main/scanLogic/graphScanLogic.ts

Unreleased bug- scanned components should be green

---

src/main/utils/builds/ciManager.ts

-----
The dependency set in CI mode should compare dependencies by their IDs.

CI - Missing dependencies

---

README.md

Add Open VSX badge

---

README.md

Rename README title

---

README.md
package.json
src/main/log/logManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/utils/configuration.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts

-----
* Allow setting the log level: 
* In some scenarios, balloon appeared on non-interactive scans.
* Use less intrusive progress bar on non-interactive scans:

Improve logging mechanism

---

package.json

Fix File Spec schema validation URL

---

package-lock.json
package.json
src/main/scanLogic/graphScanLogic.ts
src/main/treeDataProviders/issuesDataProvider.ts
src/main/types/issueCacheObject.ts
src/main/utils/translators.ts
src/test/tests/issuesDataProvider.test.ts
src/test/tests/translators.test.ts

-----
Related PR : https://github.com/jfrog/jfrog-client-js/pull/46

Add references' link to 'component issue details'

---

src/main/connect/connectionManager.ts
src/main/dependencyUpdate/dependencyUpdateManager.ts
src/main/scanLogic/componentSummaryScanLogic.ts
src/main/scanLogic/graphScanLogic.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/test/tests/scanLogic.test.ts

-----
Depends on https://github.com/jfrog/jfrog-client-js/pull/45

Improve progress indicator

---

README.md

Update readme.md - Add test status badge

---

package.json

Fix link in welcome view

---

package-lock.json
package.json
src/main/connect/connectionUtils.ts
src/main/utils/configuration.ts
src/main/utils/mavenUtils.ts

-----
Depends on https://github.com/jfrog/jfrog-client-js/pull/47

Allow configuring the number of connection retries

---

package.json
src/main/commands/commandManager.ts
src/main/connect/connectionManager.ts
src/main/constants/contextKeys.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/treeDataProviderManager.ts
src/main/treeDataProviders/treesManager.ts
src/main/utils/scanUtils.ts

-----
As soon as the user presses disconnect, the extension will try to auto-connect again if it finds credentials in the environment vars or JFrog CLI. This PR fixes this problem.

Stop auto-connecting upon pressing disconnect

---

package-lock.json

Upgrade 'terser' dependency

---

src/main/connect/connectionManager.ts

Display 'disconnected' status for new users

---

src/main/commands/commandManager.ts
src/main/log/logManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/nugetUtils.ts

Add a pop-up hint in case of a scan failure

---

src/main/utils/mavenUtils.ts

Fix typos in Maven

---

src/main/utils/mavenUtils.ts
src/main/utils/nugetUtils.ts

Change relative path to absolute path

---

src/test/tests/connectionManager.test.ts
src/test/tests/scanLogic.test.ts

Improve tests

---

package.json
src/main/commands/commandManager.ts
src/main/connect/connectionManager.ts

Remove status bar duplication and change icon positions

---

package-lock.json
package.json
src/extension.ts
src/main/commands/commandManager.ts
src/main/filter/abstractFilter.ts
src/main/treeDataProviders/dependenciesTree/treeDataProviderManager.ts
src/main/treeDataProviders/dependencyDetailsProvider.ts
src/main/treeDataProviders/generalDetailsDataProvider.ts
src/main/treeDataProviders/sourceCodeTree/sourceCodeTreeDataProvider.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts
src/test/tests/utils/testMemento.test.ts

Upgrade vscode engine to 1.64

---

.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pull-request.yml

Add Frogbot to this repository

---

.frogbot/frogbot-config.yml

Fix frogbot-config

---

.jfrog-pipelines/resources.yml
.jfrog-pipelines/snapshot.yml

Create snapshots for each commit

---

src/main/cache/issuesCache.ts
src/main/diagnostics/descriptorActionProvider.ts
src/main/log/logManager.ts
src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/main/treeDataProviders/utils/descriptorUtils.ts
src/main/types/issuesData.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/nugetUtils.ts

Adding exe ending for applicability binary in windows

---

src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/scanRunners/binaryRunner.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
src/main/treeDataProviders/issuesTree/fileTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/main/treeDataProviders/utils/descriptorUtils.ts
src/main/treeDataProviders/utils/stepProgress.ts
src/main/types/projectType.ts
src/main/utils/scanUtils.ts
src/main/webviews/detailsWebView.ts

Show reason in webview, format scanner path response and fix opening in column view

---

src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
src/main/treeDataProviders/utils/descriptorUtils.ts

Fix infected and fixed versions display for cve issues

---

package-lock.json
package.json
src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts
src/main/webviews/detailsWebView.ts

Upgrade webview to 0.1.16

---

src/main/treeDataProviders/utils/descriptorUtils.ts

Build impact path per component and issue

---

package-lock.json
package.json
src/main/commands/commandManager.ts
src/main/constants/contextKeys.ts
src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts

Add ignore rules to violations

---

package.json
src/main/scanLogic/scanManager.ts
src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/main/utils/configuration.ts
src/test/tests/fileTreeNode.test.ts
src/test/tests/issuesTreeNode.test.ts
src/test/tests/utils/treeNodeUtils.test.ts

Add root issues node tests

---

src/main/diagnostics/applicabilityActionProvider.ts

Add gutter icons for applicable issues in editor

---

src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
src/main/utils/goUtils.ts
src/test/tests/goUtils.test.ts

Add go version as direct dependency for scan

---

package-lock.json
package.json
src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts
src/main/treeDataProviders/utils/descriptorUtils.ts
src/main/types/issuesData.ts

Upgrade webview to 0.1.18

---

src/main/diagnostics/abstractFileActionProvider.ts
src/main/diagnostics/applicabilityActionProvider.ts
src/main/diagnostics/descriptorActionProvider.ts
src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
src/main/treeDataProviders/utils/descriptorUtils.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/pypiUtils.ts
src/main/utils/yarnUtils.ts
src/test/tests/descriptorTree.test.ts
src/test/tests/goUtils.test.ts
src/test/tests/maven.test.ts
src/test/tests/npmUtils.test.ts
src/test/tests/pypiUtils.test.ts
src/test/tests/yarnUtils.test.ts

Add code action jump from dependency in editor to tree

---

src/main/diagnostics/descriptorActionProvider.ts
src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/descriptorUtils.ts
src/test/tests/utils/treeNodeUtils.test.ts

Add jump from dependency in tree to location in editor

---

src/main/diagnostics/abstractFileActionProvider.ts
src/main/diagnostics/applicabilityActionProvider.ts
src/main/treeDataProviders/issuesTree/codeFileTree/codeFileTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/test/tests/issuesTreeNode.test.ts

Refactor ApplicabilityActionProvider

---

package.json

Remove unused open file command def

---

src/main/scanLogic/scanRunners/binaryRunner.ts

Remove analyzer manager env variables log

---

package-lock.json
src/main/commands/commandManager.ts
src/main/connect/connectionUtils.ts

Add user notification if free tier server is not active

---

src/main/commands/commandManager.ts

Fix disconnect command

---

src/main/commands/commandManager.ts
src/main/diagnostics/codeFileActionProvider.ts
src/main/diagnostics/descriptorActionProvider.ts
src/main/diagnostics/diagnosticsManager.ts

Better describe codeFileIssue diagnostic text

---

src/main/utils/pypiUtils.ts

Handle spaces in python script path

---

src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
src/test/tests/descriptorTree.test.ts

Remove artifact from dependency tooltip

---

src/main/treeDataProviders/issuesTree/codeFileTree/codeIssueTreeNode.ts

Fix analyzer locations to fit spec file

---

package-lock.json
package.json
src/main/treeDataProviders/issuesTree/codeFileTree/eosTreeNode.ts
src/main/utils/translators.ts

Update webview 0.1.20

---

.github/workflows/test.yml

Use maven 3.8.7 for tests

---

package-lock.json
src/main/scanLogic/scanRunners/analyzerModels.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/scanRunners/eosScan.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts

-----
FullDescription can be empty for scanners, to avoid Error when getting the text attribute (TypeError).
In addition specific more detailed log for unique CVE found

FullDescription could be empty, detailed log entry

---

src/main/connect/connectionManager.ts
src/main/scanLogic/scanManager.ts
src/main/utils/resource.ts

Fix resource update logs

---

package-lock.json
package.json
src/main/scanLogic/scanRunners/binaryRunner.ts

Update client js to 2.6.3

---

src/main/log/logUtils.ts

Clear oldest logs first when log directory is full

---

.github/workflows/release.yml

Update GitHub-Actions checkout to v3

---

.github/workflows/release.yml
.github/workflows/test.yml

Update GitHub-Actions tests.yml checkout to v3

---

.frogbot/frogbot-config.yml
.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pull-request.yml
.github/workflows/release.yml
.github/workflows/test.yml
.jfrog-pipelines/snapshot.yml

Use npm ci and update Actions

---

src/main/scanLogic/scanRunners/analyzerModels.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/scanRunners/binaryRunner.ts
src/main/scanLogic/scanRunners/eosScan.ts
src/main/treeDataProviders/utils/stepProgress.ts
src/main/utils/runUtils.ts
src/test/tests/scanAnlayzerRunner.test.ts

Add general analyzer manager tests

---

.frogbot/frogbot-config.yml
.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pull-request.yml
README.md

-----
* Removed the JF_INSTALL_DEPS_CMD variable from the Frogbot workflows, since Frogbot no longer requires it for npm.
* Removed the `frogbot-config.yml` file, since it is not needed for this reository.
* Added Frogbot badge to the README.

Simplify the Frogbot workflows & add badge

---

package-lock.json
package.json

Promote jfrog-ide-webview to version to 0.1.23

---

.github/workflows/test.yml
src/test/tests/connectionManager.test.ts
src/test/tests/integration/applicabilityIntegration.test.ts

Fix tests in Window Applicable integration

---

package.json
src/main/cache/issuesCache.ts
src/main/codeLens/abstractCodeLensProvider.ts
src/main/commands/commandManager.ts

Notify before delete cache once a week

---

package-lock.json
package.json

Update Webview to 0.1.25

---

src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/analyzerModels.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/scanRunners/binaryRunner.ts
src/main/scanLogic/scanRunners/iacScan.ts
src/main/scanLogic/scanRunners/secretsScan.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/test/tests/analyzerUtils.test.ts
src/test/tests/scanAnlayzerRunner.test.ts

Add exclude pattern for IAC Secrets

---

src/main/scanLogic/scanRunners/binaryRunner.ts

-----
Use a specific version of the Analyzer-Manager to run the advance scans instead of downloading it

Use a fixed version of the AnalyzerManager

---

src/test/tests/applicabilityScan.test.ts

Remove debug leftover

---

src/main/scanLogic/scanRunners/applicabilityScan.ts

Add ApplicabilityScan for Maven

---

src/main/scanLogic/scanRunners/binaryRunner.ts

-----
The Analyzer Manager has been updated to 1.2.4.1884897, which adds additional CVE findings for the Vulnerability Contextual Analysis scanner.

Vulnerability Contextual Analysis - Add additional CVE findings

---

package-lock.json
package.json

-----
This PR includes the following changes to the webview:
* Update SSO min version text by @Or-Geva in https://github.com/jfrog/jfrog-ide-webview/pull/33
* EOS - Add Rule ID by @Or-Geva in https://github.com/jfrog/jfrog-ide-webview/pull/32

Update webview version

---

src/main/scanLogic/scanRunners/binaryRunner.ts

Update Analyzer Manager version to 1.2.4.1908731

---

src/main/scanLogic/scanRunners/binaryRunner.ts
src/main/scanLogic/scanRunners/secretsScan.ts

-----
Add an option to ignore results found in secrets scan by adding 'jfrog-ignore' phrase above the line to ignore

Add suppression to secrets scan

---

package-lock.json
package.json

Upgrade the webview to the latest UI

---

package.json
src/main/connect/connectionManager.ts
src/main/connect/connectionUtils.ts
src/test/tests/connectionManager.test.ts

Fix connection lost detection

---

package-lock.json
package.json

Update nuget-deps-tree dependency to 0.3.1

---

package.json

Add .git to default exclusions

---

src/main/scanLogic/scanRunners/analyzerManager.ts
src/test/tests/integration/externalResourcesRepository.test.ts

Fix source code format

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Analyzer Manager Upgrade Version - 1.4.0

---

package-lock.json
package.json
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/treeDataProviders/utils/yarnImpactGraph.ts
src/test/tests/dependencyUtils.test.ts
src/test/tests/utils/treeNodeUtils.test.ts
src/test/tests/yarnImpactGraph.test.ts

-----
This new Webview version, removes `pathsCount` and The `pathsLimit` field will now be sent only when the limit is reached; otherwise, it should not be sent or filled with a negative number.
* https://github.com/jfrog/jfrog-ide-webview/pull/49

Update webview version to 0.2.12

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Analyzer manager version update to 1.6.0

---

package-lock.json
package.json
src/main/connect/connectionManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
src/main/webview/event/tasks/login.ts
src/test/tests/connectionManager.test.ts
src/test/tests/yarnImpactGraph.test.ts

-----
Include the necessary verification code to finalize the Single Sign-On (SSO) login process on the JFrog platform website.
Depends on: jfrog/jfrog-ide-webview#52

Add verification code to the SSO login view

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Analyzer manager version update to 1.6.1

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Analyzer Manager Version Update 1.6.2

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Analyzer manager updated to version 1.6.3

---

.vscode/settings.json
src/main/utils/utils.ts

Fix format & Update settings.json

---

src/main/scanLogic/scanRunners/analyzerManager.ts

-----
Always use the latest version of the Analyzer Manager binary.

Use latest version for Analyzer Manager binary

---

.github/workflows/test.yml
src/main/dependencyUpdate/dependencyUpdateManager.ts
src/main/dependencyUpdate/pnpmDependencyUpdate.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/pnpmTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/types/projectType.ts
src/main/utils/npmUtils.ts
src/main/utils/pnpmUtils.ts
src/main/utils/scanUtils.ts
src/main/utils/yarnUtils.ts
src/test/resources/pnpm/project-1/package.json
src/test/resources/pnpm/project-1/pnpm-lock.yaml
src/test/resources/pnpm/project-2/package.json
src/test/resources/pnpm/project-2/pnpm-lock.yaml
src/test/tests/pnpmUtils.test.ts

-----
Support [Pnpm package manager](https://pnpm.io/)
Test are passing (it will only work after merge since the action needs to install first):

Support Pnpm package manager

---

CONTRIBUTING.md
README.md

-----
Add `CONTRIBUTE.md` file with instructions on sub-modules that was deleted at: 
https://github.com/jfrog/jfrog-vscode-extension/pull/445/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L570

Add contribute page

---

.github/workflows/test.yml

-----
Old version and not supported by actions in MAC:

Remove node 14 tests

---

src/main/scanLogic/scanRunners/analyzerModels.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/test/resources/applicableScan/analyzerResponse.json

Fix parsing Contextual Analysis statues in response

---

src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/utils/utils.ts

Update Analyzer Manager to v1.8.8

---

.github/workflows/test.yml
src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/test/tests/integration/applicability.test.ts
src/test/tests/integration/secrets.test.ts

Update analyzer manager to v1.8.9

---

package-lock.json
package.json
src/main/treeDataProviders/issuesTree/codeFileTree/sastTreeNode.ts

-----
I updated the dependency of jfrog-ide-webview to the latest available in the project.
Made changes in the code to match this version's dependencies.

change jfrog-ide-webview version to the latest 0.2.14

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Update Analyzer Manager to v1.8.10

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Update Analyzer Manager to v1.8.13

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Update Analyzer Manager to v1.8.14

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Update Analyzer Manager to v1.13.4

---

package-lock.json

Added back package lock

---

package-lock.json
package.json

-----
updated webview to get version that includes tooltips and not applicable severity icon

Updated webview version

---

src/main/scanLogic/scanRunners/analyzerModels.ts
src/main/scanLogic/scanRunners/sastScan.ts

-----
Changed the SAST title to the short description of the rule

Changed the SAST title

---

src/main/scanLogic/scanRunners/analyzerManager.ts

-----
Update AM (1.15.2) to latest JAS and SAST versions - bug fixes and improvements

update am to 1.15.2

---

package-lock.json
package.json
src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/scanLogic/scanRunners/iacScan.ts
src/main/scanLogic/scanRunners/sastScan.ts
src/main/types/workspaceIssuesDetails.ts

-----
Added support for IAC suppression + updated the webview to version 0.4.2, in order to show the code snippet

Add support for IAC suppression

---

src/main/utils/mavenUtils.ts
src/main/utils/pomTree.ts

-----
Add debug logs so investigation will be easier if issues occur

Add debug logs for maven commands

---

releaseScripts/uploadAsset.js

-----
fixed the release assets to upload the correct data

Fix release assets
