src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts

**Steps to reproduce:**
Had a vulnerable dependency.
Removed it from package.json.
Run npm install.
The dependency was removed from our components tree - good.
It is still shown in the component details, and component issue details - not good

Unselect component after refresh

---

src/extension.ts
src/main/log/logManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
src/main/treeDataProviders/dependenciesTree/goTreeNode.ts
src/main/treeDataProviders/dependenciesTree/npmTreeNode.ts
src/main/treeDataProviders/dependenciesTree/pypiTreeNode.ts
src/main/treeDataProviders/treesManager.ts
src/main/utils/goUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/pypiUtils.ts
src/test/tests/goUtils.test.ts
src/test/tests/npmUtils.test.ts
src/test/tests/pypiUtils.test.ts

+ Use vscode [Output channel API](https://code.visualstudio.com/api/references/vscode-api#OutputChannel).
+ Add debug level information.
+ npm/go/python dependencies list error will be toasted only in slow scans.

Improve log messages

---

src/main/utils/pypiUtils.ts

Avoid `Could not scan Pypi project dependencies, because python extension is not installed` message if there aren't python files in the workspaces.

Check python extension only if there are python files

---

src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
src/main/treeDataProviders/dependenciesTree/goTreeNode.ts
src/main/treeDataProviders/dependenciesTree/npmTreeNode.ts
src/main/treeDataProviders/dependenciesTree/pypiTreeNode.ts

Increase buffer size from the default 1MiB to 10MiB.
Information on the default buffer from here: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options

Increate buffersize in child_process.spawnSync()

---

src/main/utils/pypiUtils.ts

This is an optimization - 
Activating Python extension may take some time (10+ seconds). Activate it only if there are python files.

Activate python extension only if there are python files

---

src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts
src/test/tests/goUtils.test.ts
src/test/tests/mavenUtils.test.ts
src/test/tests/npmUtils.test.ts
src/test/tests/pypiUtils.test.ts

* Add missing `async` in scanWithProgress
* To avoiding flooding the progressbar - Move most of the reports to the log manager
* Remove redundant Maven progressbar
* Print `Generating Maven Dependency Tree` to the log only when there are pom.xml files

Fix progressbar

---

src/extension.ts
src/main/commands/commandManager.ts
src/main/log/logManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts

Add JFrog status bar at the right bottom of the screen.
* Clicking on it causes showing the logs
* On success scan: ![image](https://user-images.githubusercontent.com/11367982/78368094-c90b6700-75cb-11ea-990c-4f44c246ef9d.png)
* On failed scan: ![image](https://user-images.githubusercontent.com/11367982/78368296-17206a80-75cc-11ea-81ed-b4e93c593cc9.png)
**Removed functionality**
* When a quick scan fails, the extension trigger a focus on the JFrog output logs screen.
This functionality is annoying when working on the terminal, for example, `git checkout <other branch>` almost always causes a context switch between the tabs.
* Don't take focus from the editor anymore.

Add JFrog status bar

---

.github/workflows/test.yml

Adding a dependency to `package.json` requires running `npm install`. Failing to do it, may cause a dirty local branch in tests and release jobs.
If the local branch is not clean, the release will fail during 'Publish to marketplace' phase.
We may want to avoid that by running `git diff --exit-code` in tests, after running `npm i`.
If there are any changes in the local branch, this command will fail the job.
For more information: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code

Tests - make sure branch is clean

---

package.json
src/main/commands/commandManager.ts
src/main/filter/filterManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/treesManager.ts
src/main/treeDataProviders/utils/setCredentialsNode.ts

-----
* Add 'configure credentials' view:
* Remove unused SetCredentialsNode class.
After this PR we will have 2 welcome views:
1. If credentials are not set are the project is not in Go: Show the "configure Xray details" view in the components tree.
2. If credentials are not set and the project is Go: Show the GoCenter view in the component details tree.

Add 'configure Xray details' view

---

src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts

-----
Resolves the following compilation errors:
```
'tooltip' is defined as a property in class 'TreeItem', but is overridden here in 'DependenciesTreeNode' as an accessor.ts(2611)
```
```
'description' is defined as a property in class 'TreeItem', but is overridden here in 'DependenciesTreeNode' as an accessor.ts(2611)
```
See breaking changes in Typescript 4.0: 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#properties-overriding-accessors-and-vice-versa-is-an-error

Set tooltip & description in generalInfo setter

---

src/main/utils/translators.ts
src/test/tests/translators.test.ts

-----
Fix 2 issues:
1. Xray issue's vulnerable component response may return components without fixed_versions. For example:
```json
"components": [
{
"component_id": "some component ID"
}
]
```
But the code expects:
```json
"components": [
{
"component_id": "some component ID",
"fixed_versions": ["1", "2", "..."]
}
]
```
The results are many "," in fixed version:
2. Xray issue's vulnerable component response may return duplicate fixed_versions. For example:
```json
"components": [
{
"component_id": "some component ID1",
"fixed_versions": ["1", "2"]
},
{
"component_id": "some component ID2",
"fixed_versions": ["1", "2"]
}
]
```
The result is duplication in fixed version:

Bugfix: fixed versions not displayed as expected

---

README.md

-----
* Remove broken link in Python instructions and add concrete instructions on how to activate a Python virtualenv.
* See changes here: https://github.com/yahavi/jfrog-vscode-extension/blob/readme/README.md#pypi-projects

Fix python instructions in readme

---

package-lock.json

Bump lodash to 4.17.20

---

src/main/utils/pypiUtils.ts

-----
Related issue: https://github.com/jfrog/jfrog-vscode-extension/issues/73

Print reason when 'isInVirtualEnv' fails

---

src/main/filter/filterManager.ts
src/main/filter/scopeFilter.ts
src/main/treeDataProviders/componentDetailsDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/mavenTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/nugetTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/pypiTree.ts
src/main/types/gavGeneralinfo.ts
src/main/types/generalInfo.ts
src/main/types/scope.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/translators.ts
src/test/resources/npm/dependency/package.json
src/test/tests/componentDetails.test.ts
src/test/tests/dependenciesTree.test.ts
src/test/tests/goUtils.test.ts
src/test/tests/issuesDataProvider.test.ts
src/test/tests/maven.test.ts
src/test/tests/npmUtils.test.ts
src/test/tests/nugetUtils.test.ts
src/test/tests/pypiUtils.test.ts

-----
**What is it?** 
* Add a new filter option to filter nodes in the Component Tree by dependency scopes
**How to use it?**
* Go to:  JFrog-Extention -> Filter -> Scope -> choose the scopes to be filtered.
**Supported Languages**
* NPM
* Maven

Add scope dependencies filter

---

package-lock.json
package.json
src/main/treeDataProviders/issuesDataProvider.ts
src/main/types/issue.ts
src/main/utils/translators.ts
src/test/tests/nugetUtils.test.ts
src/test/tests/translators.test.ts

-----
Depends on: https://github.com/jfrog/xray-client-js/pull/11. Tests will fail without it.
* If 1 CVEs exist add it to the tree (See image below).
* If CVEs does not exist, don't add the CVEs node.
* If more than 1 CVE exist, put them in 1 string delimited by comma (`,`), for example: `CVE-1,CVE-2`.

Add CVEs information in "Component Issue Details"

---

src/main/connect/connectionManager.ts

-----
https://github.com/jfrog/jfrog-vscode-extension/issues/78
Instead of showing `https://`, show an Xray example URL:
Same as we did here: https://github.com/jfrog/jfrog-idea-plugin/pull/89

Add example URL in connection

---

src/main/commands/commandManager.ts
src/main/dependencyUpdate/dependencyUpdateManager.ts

-----
Steps to reproduce:
1. Click on the `Update dependency` on a dependency that has more than one fixed version.
2. Instead of choosing a version, click on `Esc` or click the background.
3. Instead of stopping the update, the extension will try to update to the same version.

Update dependency should stop when non selected

---

package.json
src/main/utils/configuration.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/nugetUtils.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts
src/main/watchers/abstractWatcher.ts
src/main/watchers/watcherManager.ts

-----
Resolves #84 
Allow disabling watchers for `go.sum` and `package-lock.json`. The code watches for changes in these files and automatically triggers a scan upon changes. This feature allows unchecking file watchers through configuration.

Allow disabling scan upon changes

---

README.md
src/main/utils/configuration.ts

Allow disabling scan upon changes - readme

---

.github/workflows/test.yml
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts

-----
In npm 7, running `npm ls` produces a flat dependency tree with direct dependencies only (see https://github.com/npm/cli/blob/v7.0.0/CHANGELOG.md#npm-ls).
To get the transitive dependency tree like in versions prior to 6, we should add the `--all` flag. 
Fortunately, npm commands do not fail when providing unknown flags. Therefore we can add the `--all` flag also when running with npm<7.

Support npm 7

---

src/test/tests/connectionManager.test.ts

-----
Fix the following error in test:
> Error: Unable to write http.proxyAuthorization to Workspace Settings. This setting can be written only into User settings.

Fix Proxy authorization header test

---

README.md

-----
Add the following table in the README:
https://github.com/yahavi/jfrog-vscode-extension/tree/icons-readme#component-tree-icons

Add top severity icons to readme

---

README.md
package.json

-----
applies [JFrog File Spec JSON schema](https://raw.githubusercontent.com/jfrog/jfrog-cli/master/schema/filespec-schema.json) on the following file patterns: `**/filespecs/*.json`, `*filespec*.json` and `*.filespec`.

Apply filespec schema validation

---

package.json
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts

-----
May resolve #109 
* Change activation event from `*` to `onStartupFinished`
* Make scan async

Bugfix: unresponsive extension

---

src/main/scanCache/scanCacheManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts

-----
May help with #109 
During refresh dependencies, the extension populates `componentsToScan` set to be used during the Xray scan.
This object is a class variable, although we don't really need it after the scan ends.
Let's make it a local variable to allow the GC to clear it at the end of the scan.

Don't hold components to scan after scan finished

---

src/main/connect/connectionUtils.ts

Blank dialog box when connection details are wrong

---

src/main/utils/pypiUtils.ts

-----
May fix #73
* The `pythonPath` setting is deprecated. That means that the python executable details can no longer be retrieved from this setting - https://devblogs.microsoft.com/python/python-in-visual-studio-code-july-2021-release/#selecting-a-python-interpreter-no-longer-modifies-workspace-settings. Instead of using it, use [getExecutionDetails](https://github.com/microsoft/vscode-python/blob/main/src/client/api.ts#L67) API.
* In some cases the Python extension is already active and we try to activate it again. This returns an error, therefore we should check before activating it.

Get python exec path using getExecutionDetails

---

resources/python/pipDepTree.py

-----
The old pipdeptree had compatibility issues with pip 21.3, which this update fixes.

pipdeptree update

---

src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/utils/npmUtils.ts
src/test/tests/npmUtils.test.ts

Fix npm ls scope to be compatible with all npm verisons

---

src/main/dependencyUpdate/dependencyUpdateManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts

-----
Fix the following errors:
1. > Exception has occurred: TypeError: Cannot read property 'length' of undefined
t /Users/yahavi/code/jfrog-vscode-extension/dist/extension.js:74287:48
at Array.some (<anonymous>)
at GoTreeNode.upgradableDependencies (/Users/yahavi/code/jfrog-vscode-extension/dist/extension.js:74287:14)
2. > Command failed: mvn versions:use-dep-version -DgenerateBackupPoms=false -Dincludes=com.thoughtworks.xstream:xstream -DdepVersion=[1.4.18]

Bug fix - unable to upgrade dependency to a fixed version

---

src/test/tests/connectionManager.test.ts

-----
Fix the following error:
> AssertionError: expected 'jfrog-vscode-extension/1.10.0' to match /^jfrog-vscode-extension\/\d.\d.\d$/

Fix user agent header test

---

src/main/scanCache/buildsScanCache.ts
src/main/utils/builds/ciManager.ts

-----
* Support long build name and numbers by encoding with sha1 instead of base64 (same as https://github.com/jfrog/ide-plugins-common/pull/59)
* In some rare cases, the AQL results may return a path to a file that doesn't actually exist. Make sure not to crash in these cases.
* After replacing the project key or platform URL, the cache dir must be replaced too. Otherwise, the builds in the cache may be mixed up.

CI - Build not found issues

---

src/main/utils/builds/ciManager.ts

-----
Currently all attempt to look for the build in the cache fails, because the timestamp string contains .json in the end.
**Explanation:**
The results of the AQL query are: `repo`, `file`, `path` triple.
The `projectkey` is the first part of the repository name.
`buildName` is path, since it is the build-info directory name.
The file is: `buildNumber`-`timestamp`.json. 
|           |          Repo          |          Path          |            Name            |
|-----------|:----------------------:|:----------------------:|:--------------------------:|
| pattern   | `projectKey`-build-info            | `buildName`              | `buildNumber`-`timestamp`.json |
| example-1 | artifactory-build-info | jfrog-vscode-extension | 1-1639300304168.json       |
| example-2 | ecosys-build-info …

CI - Build info not loaded properly from cache

---

src/main/utils/mavenUtils.ts

-----
Mismatch position on pom.xml for two or more dependencies with the same `groupId `. The following dependencies, for example, will override each other's position:
```
...
<dependency>
<groupId>org.jenkins-ci.plugins</groupId>
<artifactId>ssh-credentials</artifactId>
<version>1.15</version>
</dependency>
<dependency>
<groupId>org.jenkins-ci.plugins</groupId>
<artifactId>credentials</artifactId>
<version>2.2.1</version>
</dependency>
...
```

Bugfix - Incorrect dependencies location on pom.xml

---

src/main/commands/commandManager.ts
src/main/connect/connectionManager.ts
src/main/connect/connectionUtils.ts
src/main/log/logManager.ts
src/main/treeDataProviders/dependenciesTree/buildsDataProvider.ts
src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts

-----
The connection status to Xray is added in this PR.

Add connection status

---

src/main/connect/connectionManager.ts
src/main/utils/mavenUtils.ts
src/test/tests/scanLogic.test.ts

-----
* Top severity of an existing component in Xray should be normal
* Top severity of a non-existed component in Xray in summary/component should be normal (old logic)

Fix ConnectionManager tests

---

src/main/diagnostics/descriptorActionProvider.ts
src/main/diagnostics/diagnosticsManager.ts
src/main/log/logManager.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts

-----
On scan end the diagnostics opened files with issues when they were closed.
Also on go error in install we showed 2 notification to the users. removed the one with the actual error, only logging now.

Fix file opening on scan end

---

src/main/treeDataProviders/issuesTree/fileTreeNode.ts
src/test/tests/fileTreeNode.test.ts
src/test/tests/utils/treeNodeUtils.test.ts

Adding tests for FileTreeNode

---

src/main/commands/commandManager.ts

-----
Left over from https://github.com/jfrog/jfrog-vscode-extension/pull/262

Restructuring code

---

package.json

-----
Disconnect command was used when the client is already disconnected.

Use connect command when needed, fix command icon

---

src/main/dependencyUpdate/dependencyUpdateManager.ts
src/main/dependencyUpdate/goDependencyUpdate.ts
src/main/dependencyUpdate/mavenDependencyUpdate.ts
src/main/dependencyUpdate/npmDependencyUpdate.ts
src/main/dependencyUpdate/nugetDependencyUpdate.ts
src/main/dependencyUpdate/yarnDependencyUpdate.ts
src/main/diagnostics/descriptorActionProvider.ts
src/main/scanLogic/scanGraphLogic.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/mavenTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/nugetTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/pypiTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/virtualEnvPypiTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/utils/goUtils.ts
src/main/utils/mavenUtils.ts
src/main/utils/npmUtils.ts
src/main/utils/nugetUtils.ts
src/main/utils/pomTree.ts
src/main/utils/pypiUtils.ts
src/main/utils/scanUtils.ts
src/main/utils/yarnUtils.ts
src/test/tests/maven.test.ts
src/test/tests/nugetUtils.test.ts

-----
Improvements:
* Fix bug - tree only showed one descriptor type even if multiple types exists in the same directory
* Show .csproj / packages.config files instead of .sln files in tree
* Show hint if the number of parsed projects is different than the number of actual .csproj files
* Locate dependencies positions in descriptors to show diagnostics
* Update dependency version to fix issues

Nuget improvements

---

src/main/scanLogic/scanRunners/analyzerModels.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/virtualEnvPypiTree.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/analyzerUtils.ts

-----
Fix parsing the applicable scan result.
We also get now the pass result (i.e the not applicable CVE) we don't need to infer those our self.
pass result does not contain location

Add pass kind to applicable result

---

.github/workflows/test.yml
package-lock.json
package.json
src/main/treeDataProviders/utils/dependencyUtils.ts

Promote jfrog-client-js to version to 2.6.2, fix impact root name and test for mac

---

src/main/treeDataProviders/issuesTree/fileTreeNode.ts
src/test/tests/fileTreeNode.test.ts

-----
`./ec2\main.tf` --> `.\ec2\main.tf`

Fix relative path display for file in windows

---

src/main/utils/resource.ts

-----
If the remote checksum could not be fetched or not exists in the header:
1. Add warning log to inform the user
2. Continue update without comparing and replace old files even if they are the same

Add warnning log if checksum header not exists

---

src/test/tests/translators.test.ts

Add tests to translators for webview and analyzer

---

src/main/scanLogic/scanRunners/binaryRunner.ts

-----
We only need to add the protocol prefix if we are getting the proxy URL from the VS-code config and not from the Environment variables

Only add protocol prefix if proxy is from config

---

package-lock.json
package.json
src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/scanRunners/binaryRunner.ts
src/main/scanLogic/scanRunners/eosScan.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/treeDataProviders/utils/stepProgress.ts
src/main/utils/runUtils.ts
src/main/utils/scanUtils.ts
src/test/tests/runUtils.test.ts

-----
* Adding timeout after 5min to each run of analyzer manager binary
* Fix cancel request to apply request for all scans and operations
* Add tests to running tasks with timeout and checking cancel

Add timeout to analyzer scans

---

.github/workflows/test.yml

-----
In maven 3.9.0 a bug in apache was included that failed our tests. 
we made sure to run on constant version 3.8.7: https://github.com/jfrog/jfrog-vscode-extension/commit/59723efb1b70d3bd1203cd83de1903ec32619496, https://github.com/jfrog/jfrog-vscode-extension/commit/860c1d2f42653749bf78f0d81dc18933d743c4bc
In version 3.9.1 this bug was fixed and the tests are successful now, we should remove this to use the latest

Remove constant maven version for tests

---

package-lock.json
package.json

-----
add ability to set the timeout for requests

Promote jfrog-client-js to version to 2.6.5

---

package.json
src/main/connect/connectionUtils.ts
src/main/utils/configuration.ts
src/test/tests/connectionManager.test.ts
src/test/tests/utils/utils.test.ts

-----
Also fixes the tests that httpbin always falls, we try 60 time until it passes only for those tests
depend on https://github.com/jfrog/jfrog-vscode-extension/pull/332
that includes https://github.com/jfrog/jfrog-client-js/pull/81

Add option to set timeout in settings

---

.vscode/launch.json

-----
OutFiles should be set to the directory where the source map files are generated for debugging vscode-extension.

Update debug configuration

---

src/main/treeDataProviders/utils/analyzerUtils.ts
src/test/tests/analyzerUtils.test.ts

Fix Windows tests for parsing path

---

src/main/utils/scanUtils.ts

-----
left over that logs info if scan not supported instead of debug and prevent to log in debug

Remove info log when scan not supported

---

src/main/utils/mavenUtils.ts

-----
Fixing issue when the user is using a directory with whitespace in it. causes an error when running a maven command that expect a path as an argument causing the parsing of the command to fail.
adding " to wrap the path text to appear as a single argument for all cases

Fix run for whitespace in path of MavenReader

---

package.json

Fix connect icon path in resources

---

src/main/scanLogic/scanRunners/binaryRunner.ts

-----
Removed msg that error log was generated if the error is of type NotSupported
Old:
```
[DEBUG - 12:33:01 PM] iac-scan-modules is not supported in the current Analyzer Manager version
[ERR - 12:33:01 PM] AnalyzerManager run iac-scan-modules on c:\Git\dlp-repo\dlp-cloud ended with error, scan log was generated at C:\Users\pv732260\.jfrog-vscode-extension\issues\logs\dlp-cloud-iac-scan-modules-1687158181150.log
```
New:
```
[DEBUG - 12:33:01 PM] iac-scan-modules is not supported in the current Analyzer Manager version
```

Remove err log if not supported scan

---

src/main/scanLogic/scanManager.ts
src/main/utils/resource.ts
src/main/utils/utils.ts

-----
When downloading AnalyzerManager, removing old version didn't wait, allowing the extract method to finish before deleting the old content resulting in removing the new analyzer manager as well.
This was the root caused of the following log that was shown:
```[DEBUG - 3:35:21 PM] Applicability runner could not find binary to run```

Fix - Download AnalyzerManager async issue

---

src/main/treeDataProviders/utils/analyzerUtils.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/utils/scanUtils.ts
src/main/utils/utils.ts
src/test/tests/applicabilityScan.test.ts
src/test/tests/dependencyUtils.test.ts

-----
* Scan Contextual Analysis (Applicability Scan) per workspace and type and not for each descriptor. (Saves time and duplicate scans)
* in addition fix an issue where multiple descriptors can add ApplicableTreeNode for the same CVE applicable location

Scan Applicable issues per workspace and not per descriptor

---

src/main/commands/commandManager.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/webview/webview.ts

-----
Closes an open webview page on a refresh scan

Close old web view page on refresh

---

src/main/utils/translators.ts
src/test/tests/translators.test.ts

-----
AnalyzerManager didn't apply the log level passed to it.
Fix - AnalyzerManager expect log level to be passed with Upper case.

Apply uppercase log level in AnalyzerManager

---

src/main/scanLogic/scanRunners/binaryRunner.ts
src/main/utils/scanUtils.ts
src/main/utils/translators.ts
src/test/tests/scanAnlayzerRunner.test.ts

-----
AnalyzerManager version `1.2.4.1858388` added error 55 (not supported by OS)

Add warning in case os not supported the scanners

---

package.json

-----
Don't allow exclusion pattern without content after a comma like the following:
`**/*{test,}*`
`**/*{test,venv,node_modules,target,}*`
will end up with pattern: `**/**/**` for scanners, skipping all files

Block exclusion pattern empty after comma

---

.github/workflows/detect-svg-in-readme.yml
README.md

-----
Due to the limitation of GitHub Actions badges being available exclusively in SVG format, we permit only the usage of GitHub Actions badges to be in the format of SVG.

Restrict the usage of SVG-formatted badges to only GitHub Actions badge

---

src/main/cache/cacheManager.ts
src/main/cache/cacheRecord.ts
src/main/treeDataProviders/utils/analyzerUtils.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/types/workspaceIssuesDetails.ts
src/main/utils/pypiUtils.ts
src/test/tests/applicabilityScan.test.ts

-----
Due to the [limitations](https://github.com/tox-dev/pipdeptree/issues/277#issuecomment-1671932271) of pipdeptree, direct dependencies may not always be captured in Python projects if they are also present as indirect dependencies. This could lead to the possibility of missing certain CVEs during the Contextual Analysis scan. To prevent this, we make sure to send all CVEs to the Contextual Analysis.

Contextual Analysis - Scan all CVEs for Python projects

---

package-lock.json
package.json

Bump semver from 7.5.2 to 7.5.4

---

src/main/treeDataProviders/utils/analyzerUtils.ts

-----
Fix - treating the virtual environment the same as the descriptor taking the dir of there full path for scanning CA.

Fix scanning wrong directory in CA for venv

---

.github/workflows/test.yml
src/main/webview/webviewManager.ts
src/main/webview/webviewTab.ts

-----
Workaround for VS-Code remote development environments -
Delay the initial page load to ensure proper message delivery in the Webview.
This is necessary because in the Webview, messages are only delivered when the Webview is alive.

Wait before loading a page at the first time

---

package.json
src/main/cache/cacheManager.ts
src/main/commands/commandManager.ts
src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
src/main/treeDataProviders/treesManager.ts

-----
This pull request introduces a new command to the JFrog extension, allowing users to delete the cache of the currently opened workspace associated with the extension.

Add a new command for deleting caches

---

src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts

-----
This pull request fixes the issue where yarn dependencies were receiving an incorrect 'npm' type, resulting in no diagnostics or autofix. The underlying problem stems from the fact that Xray's response for yarn vulnerable dependencies was type as 'npm,' and this was applied to each vulnerable yarn dependency.
To address this, the vulnerable package type is now extended from the root project identified by the extension.

Yarn - Fix incorrect package type

---

src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
src/main/treeDataProviders/utils/analyzerUtils.ts

-----
This problem pertains to the Applicability scan in Python projects:
When gathering the directories for running the applicability scan, we erroneously select the parent directory of the workspace instead of the workspace itself. This can lead to running the applicability scan on irrelevant directories, ultimately resulting in a timeout issue in my environment.
In a more technical sense, we perform `fileScanBundle instanceof EnvironmentTreeNode` instead of `fileScanBundle.dataNode instanceof EnvironmentTreeNode`.

Applicability scanner scans the venv parent dir

---

src/main/scanLogic/scanGraphLogic.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/mavenTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/nugetTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/pypiTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
src/main/treeDataProviders/utils/dependencyUtils.ts
src/main/treeDataProviders/utils/yarnImpactGraph.ts
src/main/types/projectDetails.ts
src/main/utils/yarnUtils.ts
src/test/tests/dependencyUtils.test.ts
src/test/tests/goUtils.test.ts
src/test/tests/utils/treeNodeUtils.test.ts
src/test/tests/yarnImpactGraph.test.ts

-----
Prior to this PR, there was an issue with the way Yarn calculated the impact graph. The problem intruduced from using the 'yarn list' output. The 'yarn list' output did not accurately represent the project's dependencies as it removed duplicate leaves and flattened the tree structure.
In order to resolve this issue, this PR changes the following:
1. Instead of constructing the entire dependency tree, we now compute only a partial tree. This partial tree specifically represents the paths from the project's root to the vulnerable dependencies only. This modification eliminates the need to calculate the entire tree, which not only reduces memory consumption but also aligns with our goal of displaying **only** paths to vulnerable dependencies.
2. Rather than relying on `yarn list`, we …

Yarn - Fix incorrect impact graph

---

package.json
src/main/commands/commandManager.ts
src/main/utils/utils.ts

-----
The navigation tool bar now includes a Feedback button. By clicking on it, the user will be redirected to the 'Product Feedback' category on Github.

Add Feedback button

---

src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/scanRunners/jasRunner.ts
src/main/scanLogic/scanRunners/sastScan.ts
src/main/utils/jfrogAppsConfig/jfrogAppsConfig.ts
src/test/tests/appsConfig.test.ts
src/test/tests/iacScan.test.ts
src/test/tests/integration/iac.test.ts
src/test/tests/integration/secrets.test.ts
src/test/tests/sastScan.test.ts
src/test/tests/scanAnlayzerRunner.test.ts
src/test/tests/secretsScan.test.ts

-----
* Remove leftovers from JasRunners log message and fix an issue where the SAST log message shows undefined for skip-folder
* When examining the [JFrog Applications Config](https://github.com/jfrog/jfrog-apps-config#jfrog-applications-config), note that the source_root has an incorrect default value when using debug mode. Essentially, this issue arises in debug mode when a configuration file exists without source_root, leading to the use of the original VSCode extension source code instead of the current project used in debug mode. The underlying cause of this problem can be traced back to the use of `__dirname`.

Change SAST log messages and  update config default root

---

src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
src/main/utils/goUtils.ts
src/test/resources/go/embedProject/go.mod
src/test/resources/go/embedProject/main.go
src/test/resources/go/project2/go.sum
src/test/tests/goUtils.test.ts

-----
Projects in Go that involve embedded files encounter an error when attempting to construct the dependency tree.
The issue place in how we convert all "replace" labels in the go.mod file from relative to absolute paths before gathering dependencies for all projects. During this process, we exclude any files that do not have a ".go" extension. Consequently, this exclusion results in missing embedded files, leading to an error when using the "go list" command. 
As a solution, we restrict the exclusion to specific, well-known folders that are safe to omit, such as "testdata" or ".git."
Fix https://github.com/jfrog/jfrog-vscode-extension/issues/372

Go - Support projects with embed files

---

src/main/utils/goUtils.ts

-----
When conducting a scan on a Go project, it's crucial to include the examination of test data for potential vulnerabilities in dependencies. For instance, the [FrogBot repository](https://github.com/jfrog/frogbot/blob/master/scanpullrequest/scanallpullrequests_test.go#L8) utilizes specific dependencies within its testdata.

Go - Scan dependencies vulnerabilities for test data

---

src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/jasRunner.ts
src/main/scanLogic/sourceCodeScan/jasRunnerFactory.ts
src/test/tests/integration/JasRunnerFactory.test.ts
src/test/tests/utils/treeNodeUtils.test.ts

-----
When running on Windows, JFrog's configuration has a bad root path. In order to resolve the root project path, we use a different API

Use the platform specific path for JFrog config

---

src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/webview/event/eventManager.ts
src/main/webview/event/eventSender.ts
src/main/webview/webviewSidebar.ts
src/main/webview/webviewTab.ts
src/test/tests/integration/applicability.test.ts
src/test/tests/webview/event/eventManager.test.ts

-----
Before this pull request, there was a potential for the Webview to take longer to load than the duration between the IDE sending the first request to the Webview. To address this issue, we now ensure that we wait for a signal indicating the completion of the webview's full loading process before sending any requests.
Dependent on: 
* https://github.com/jfrog/jfrog-ide-webview/pull/51

Make sure the webview is loaded before sending requests

---

src/main/utils/goUtils.ts
src/test/tests/goUtils.test.ts

-----
When scanning project with Go version 1.x, the `SemVer` can't parse the string to create a version object:
This fix adds a `.0` suffix to the version so it can parse, allowing to scan them

Fix Go scanning when Go version is partial

---

src/test/tests/pnpmUtils.test.ts

-----
pnpm not supported at node 14 or less: https://pnpm.io/installation
adding skip tests

Dont run pnpm tests in node 14 or less

---

src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/treeDataProviders/issuesTree/codeFileTree/codeIssueTreeNode.ts

-----
```
[ERR - 18:12:36] Error: Illegal argument: character must be non-negative
```
There is a different mapping that vscode expects as positions at file. 
For vscode the minimum value (i.e first row/col) is 0 while the results mapped to it is 1 from the scanners.
Fixing a bug that occurs when issues discovered at JAS scans (CA and secrets) have a location with row/col 0:
```
"region": {
"snippet": {
"text": "*******"
},
"endColumn": 0,
"endLine": 3,
"startColumn": 0,
"startLine": 3
},
```

Fix - character must be non-negative in JAS issues with a location value of 0

---

package.json
src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/utils/configuration.ts

-----
Add option to control the Analyzer Manager version used for scanning

Config AnalyzerManager version

---

src/main/treeDataProviders/issuesTree/codeFileTree/codeIssueTreeNode.ts
src/main/utils/configuration.ts

-----
There is a bug in the CI mode configurations. It did not took the actual configurations since there was a bug in the id of the configuration we used.
Expected:
```
view.ciIntegration.buildNamePattern
```
Found:
```
xray.ciIntegration.buildNamePattern
```

Fix build pattern configuration id

---

.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pull-request.yml
.github/workflows/release.yml
.github/workflows/test.yml
package.json
src/main/scanLogic/scanRunners/sastScan.ts
src/main/treeDataProviders/issuesTree/codeFileTree/codeIssueTreeNode.ts
src/main/utils/configuration.ts

-----
1. Prepare a custom json rules file with your rules:
```json
[
{
"name": "custom-rule",
"message": "User-controlled data used as argument to math.sqrt",
"finder": {
"type": "FlowFinder",
"sources": {
"type": "calls",
"names": [
"input"
]
},
"sinks": {
"type": "calls",
"names": [
"math.sqrt"
]
}
},
"cwe": null,
"description": "User-controlled square root",
"severity": "high",
"tags": []
}
]
```
2. Provide the **Absolute** path to the user custom rule file at the extension's new configuration.
3. Rescan your workspace.

Add Custom rules to SAST scan

---

package.json
src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/utils/configuration.ts

-----
* Use AnalyzerManager v1.8.3 (const version per vscode extension version).
You can still specified a specific version in the config

Use const AnalyzerManager version 1.8.3

---

src/main/utils/utils.ts

-----
For windows user, when trying to extract the AM v1.8.9+ extraction resulted in max files reached.

Fix - Analyzer manager extraction for Windows

---

src/main/scanLogic/scanRunners/analyzerManager.ts

Update Analyzer Manager to v1.9.7

---

src/main/scanLogic/scanRunners/analyzerManager.ts

-----
Fix AM 1.11.8 - Fix SAST Scanner for old OS support

Update am 1.11.8

---

package-lock.json
package.json
src/main/diagnostics/descriptorActionProvider.ts
src/main/scanLogic/scanManager.ts
src/main/scanLogic/scanRunners/analyzerManager.ts
src/main/scanLogic/scanRunners/applicabilityScan.ts
src/main/scanLogic/sourceCodeScan/supportedScans.ts
src/main/treeDataProviders/utils/analyzerUtils.ts

-----
Update Webview dependency to `v0.3.0`

Update Webview v0.3.0

---

src/main/connect/connectionUtils.ts

-----
When adding proxy to the vs code settings, the Analyzer Manager is outputting this error log: "proxyconnect tcp: dial tcp: lookup - no such host".
The VS code plugin was creating the proxy URL with the port written twice, for example: 123.11.1.11:8080:8080, instead of 123.11.1.11:8080. Than it was transferring it to the Analyzer Manager in the wrong format.
This PR is fixing the bug and changing the GetProxyConfig() function to parse the proxy URL correctly.

Fixed proxy configuration to retrieve the correct proxy details

---

src/main/scanLogic/scanRunners/analyzerManager.ts

-----
When passing a protocol to the vscode configuration, we were parsing the value and populating both `HTTP` and `HTTPS` proxy env vars and passing them to the AM. this has caused issue when proxy was `http`.

Only pass the configure proxy protocol to AM

---

src/main/treeDataProviders/utils/dependencyUtils.ts
src/test/tests/dependencyUtils.test.ts

-----
Fixing an issue with the logs,
Instead of outputting the actual unique CVE detected, we output a wrong number (calculating the unique number of dependencies with issue)
This PR fixes this issue and add the actual unique CVE in addition to the number of deps with issues

Log unique number of CVE discovered per descriptor

---

src/main/scanLogic/scanRunners/analyzerManager.ts

-----
Added the needed env var for version request to am
plus upgraded AM version where the info logs arent written to the std.err

Fixed AM version log error

---

package-lock.json
package.json

-----
Depends On:
* https://github.com/jfrog/nuget-deps-tree/pull/43
* https://github.com/jfrog/nuget-deps-tree/pull/44

Fix Nuget Dependency Detection bugs
